service: service-4-Login

provider:
  name: aws
  runtime: nodejs12.x

  stage: dev
  region: us-east-1

functions:
  4_1a_ValidCredentials:
    handler: handler.validCredentials_v1
    events:
      - https:
          path: /v1/login/valid_credentials
          method: post

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 1
    maxConcurrentRequests: 1